version: '3.4'

services:
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=mongodb+srv://sstec-admin:w37ChqyNRZvnxtqL@cluster0.dw2cy.mongodb.net
    ports:
      - "8000:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CacheSettings__ConnectionString=basketdb:6379
    depends_on:
      - basketdb
    ports:
      - "8001:80"