version: '3.4'

services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=mongodb+srv://sstec-admin:w37ChqyNRZvnxtqL@cluster0.dw2cy.mongodb.net
    ports:
      - "8000:80"